export const C = {
    ADD_COVID: "ADD_COVID",
    SORT_COVID: "SORT_COVID",
    ADD_TIMESET: "ADD_TIMESET",
    ADD_COUNTRY: "ADD_COUNTRY",
    REMOVE_COUNTRY: "REMOVE_COUNTRY",
    LOADING_MESSAGE: "LOADING_MESSAGE",
    SET_MONTH: "SET_MONTH",
    BTN_CLICKED: "BTN_CLICKED",
    CLICKED_BTN: "CLICKED_BTN"
}